// This file was generated by gir (https://github.com/gtk-rs/gir @ ad40c01)
// from gir-files (https://github.com/gtk-rs/gir-files @ 5b96546)
// DO NOT EDIT

use glib::object::IsA;
use glib::translate::*;
use glib::GString;
use gmime_sys;
use std::fmt;
use FormatOptions;
use ParamList;
use ParserOptions;

glib_wrapper! {
    pub struct ContentDisposition(Object<gmime_sys::GMimeContentDisposition, gmime_sys::GMimeContentDispositionClass, ContentDispositionClass>);

    match fn {
        get_type => || gmime_sys::g_mime_content_disposition_get_type(),
    }
}

impl ContentDisposition {
    pub fn new() -> ContentDisposition {
        unsafe {
            from_glib_full(gmime_sys::g_mime_content_disposition_new())
        }
    }

    pub fn parse(options: Option<&ParserOptions>, str: &str) -> Option<ContentDisposition> {
        unsafe {
            from_glib_full(gmime_sys::g_mime_content_disposition_parse(mut_override(options.to_glib_none().0), str.to_glib_none().0))
        }
    }
}

impl Default for ContentDisposition {
    fn default() -> Self {
        Self::new()
    }
}

pub const NONE_CONTENT_DISPOSITION: Option<&ContentDisposition> = None;

pub trait ContentDispositionExt: 'static {
    fn encode(&self, options: Option<&FormatOptions>) -> Option<GString>;

    fn get_disposition(&self) -> Option<GString>;

    fn get_parameter(&self, name: &str) -> Option<GString>;

    fn get_parameters(&self) -> Option<ParamList>;

    fn is_attachment(&self) -> bool;

    fn set_disposition(&self, value: &str);

    fn set_parameter(&self, name: &str, value: &str);
}

impl<O: IsA<ContentDisposition>> ContentDispositionExt for O {
    fn encode(&self, options: Option<&FormatOptions>) -> Option<GString> {
        unsafe {
            from_glib_full(gmime_sys::g_mime_content_disposition_encode(self.as_ref().to_glib_none().0, mut_override(options.to_glib_none().0)))
        }
    }

    fn get_disposition(&self) -> Option<GString> {
        unsafe {
            from_glib_none(gmime_sys::g_mime_content_disposition_get_disposition(self.as_ref().to_glib_none().0))
        }
    }

    fn get_parameter(&self, name: &str) -> Option<GString> {
        unsafe {
            from_glib_none(gmime_sys::g_mime_content_disposition_get_parameter(self.as_ref().to_glib_none().0, name.to_glib_none().0))
        }
    }

    fn get_parameters(&self) -> Option<ParamList> {
        unsafe {
            from_glib_none(gmime_sys::g_mime_content_disposition_get_parameters(self.as_ref().to_glib_none().0))
        }
    }

    fn is_attachment(&self) -> bool {
        unsafe {
            from_glib(gmime_sys::g_mime_content_disposition_is_attachment(self.as_ref().to_glib_none().0))
        }
    }

    fn set_disposition(&self, value: &str) {
        unsafe {
            gmime_sys::g_mime_content_disposition_set_disposition(self.as_ref().to_glib_none().0, value.to_glib_none().0);
        }
    }

    fn set_parameter(&self, name: &str, value: &str) {
        unsafe {
            gmime_sys::g_mime_content_disposition_set_parameter(self.as_ref().to_glib_none().0, name.to_glib_none().0, value.to_glib_none().0);
        }
    }
}

impl fmt::Display for ContentDisposition {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "ContentDisposition")
    }
}
