// This file was generated by gir (https://github.com/gtk-rs/gir @ 9e3cb65)
// from gir-files (https://github.com/gtk-rs/gir-files @ b215ee8+)
// DO NOT EDIT

use Filter;
use glib::object::Cast;
use glib::translate::*;
use gmime_sys;
use std::fmt;

glib_wrapper! {
    pub struct FilterHTML(Object<gmime_sys::GMimeFilterHTML, gmime_sys::GMimeFilterHTMLClass, FilterHTMLClass>) @extends Filter;

    match fn {
        get_type => || gmime_sys::g_mime_filter_html_get_type(),
    }
}

impl FilterHTML {
    pub fn new(flags: u32, colour: u32) -> FilterHTML {
        unsafe {
            Filter::from_glib_full(gmime_sys::g_mime_filter_html_new(flags, colour)).unsafe_cast()
        }
    }
}

pub const NONE_FILTER_HTML: Option<&FilterHTML> = None;

impl fmt::Display for FilterHTML {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "FilterHTML")
    }
}
