// This file was generated by gir (https://github.com/gtk-rs/gir @ 7f5a2b5)
// from gir-files (https://github.com/gtk-rs/gir-files @ 4740f5e+)
// DO NOT EDIT

use Filter;
use ffi;
use glib::object::Downcast;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::mem;
use std::ptr;

glib_wrapper! {
    pub struct FilterStrip(Object<ffi::GMimeFilterStrip, ffi::GMimeFilterStripClass>): Filter;

    match fn {
        get_type => || ffi::g_mime_filter_strip_get_type(),
    }
}

impl FilterStrip {
    pub fn new() -> FilterStrip {
        unsafe {
            Filter::from_glib_full(ffi::g_mime_filter_strip_new()).downcast_unchecked()
        }
    }
}

impl Default for FilterStrip {
    fn default() -> Self {
        Self::new()
    }
}
