// This file was generated by gir (https://github.com/gtk-rs/gir @ ad40c01)
// from gir-files (https://github.com/gtk-rs/gir-files @ 5b96546)
// DO NOT EDIT

use glib::object::Cast;
use glib::translate::*;
use gmime_sys;
use std::fmt;
use Filter;

glib_wrapper! {
    pub struct FilterEnriched(Object<gmime_sys::GMimeFilterEnriched, gmime_sys::GMimeFilterEnrichedClass, FilterEnrichedClass>) @extends Filter;

    match fn {
        get_type => || gmime_sys::g_mime_filter_enriched_get_type(),
    }
}

impl FilterEnriched {
    pub fn new(flags: u32) -> FilterEnriched {
        unsafe {
            Filter::from_glib_full(gmime_sys::g_mime_filter_enriched_new(flags)).unsafe_cast()
        }
    }
}

pub const NONE_FILTER_ENRICHED: Option<&FilterEnriched> = None;

impl fmt::Display for FilterEnriched {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "FilterEnriched")
    }
}
