// This file was generated by gir (https://github.com/gtk-rs/gir @ 00040a2)
// from gir-files (https://github.com/gtk-rs/gir-files @ 5b96546)
// DO NOT EDIT

use crate::Filter;
use glib::object::Cast;
use glib::translate::*;
use std::fmt;

glib::wrapper! {
    pub struct FilterStrip(Object<ffi::GMimeFilterStrip, ffi::GMimeFilterStripClass>) @extends Filter;

    match fn {
        get_type => || ffi::g_mime_filter_strip_get_type(),
    }
}

impl FilterStrip {
    #[doc(alias = "g_mime_filter_strip_new")]
    pub fn new() -> FilterStrip {
        unsafe {
            Filter::from_glib_full(ffi::g_mime_filter_strip_new()).unsafe_cast()
        }
    }
}

impl Default for FilterStrip {
    fn default() -> Self {
        Self::new()
    }
}

pub const NONE_FILTER_STRIP: Option<&FilterStrip> = None;

impl fmt::Display for FilterStrip {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("FilterStrip")
    }
}
