// This file was generated by gir (https://github.com/gtk-rs/gir @ 7f5a2b5)
// from gir-files (https://github.com/gtk-rs/gir-files @ 4740f5e+)
// DO NOT EDIT

use Filter;
use ffi;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::mem;
use std::ptr;

glib_wrapper! {
    pub struct FilterFrom(Object<ffi::GMimeFilterFrom, ffi::GMimeFilterFromClass>): Filter;

    match fn {
        get_type => || ffi::g_mime_filter_from_get_type(),
    }
}

impl FilterFrom {
    //pub fn new(mode: /*Ignored*/FilterFromMode) -> FilterFrom {
    //    unsafe { TODO: call ffi::g_mime_filter_from_new() }
    //}
}
