// This file was generated by gir (https://github.com/gtk-rs/gir @ 00040a2)
// from gir-files (https://github.com/gtk-rs/gir-files @ 5b96546)
// DO NOT EDIT

use crate::Filter;
#[cfg(any(feature = "v3_2", feature = "dox"))]
#[cfg_attr(feature = "dox", doc(cfg(feature = "v3_2")))]
use crate::OpenPGPData;
#[cfg(any(feature = "v3_2", feature = "dox"))]
#[cfg_attr(feature = "dox", doc(cfg(feature = "v3_2")))]
use glib::object::Cast;
use glib::object::IsA;
use glib::translate::*;
use std::fmt;

glib::wrapper! {
    pub struct FilterOpenPGP(Object<ffi::GMimeFilterOpenPGP, ffi::GMimeFilterOpenPGPClass>) @extends Filter;

    match fn {
        get_type => || ffi::g_mime_filter_openpgp_get_type(),
    }
}

impl FilterOpenPGP {
    #[cfg(any(feature = "v3_2", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "v3_2")))]
    #[doc(alias = "g_mime_filter_openpgp_new")]
    pub fn new() -> FilterOpenPGP {
        unsafe {
            Filter::from_glib_full(ffi::g_mime_filter_openpgp_new()).unsafe_cast()
        }
    }
}

#[cfg(any(feature = "v3_2", feature = "dox"))]
#[cfg_attr(feature = "dox", doc(cfg(feature = "v3_2")))]
impl Default for FilterOpenPGP {
    fn default() -> Self {
        Self::new()
    }
}

pub const NONE_FILTER_OPEN_PGP: Option<&FilterOpenPGP> = None;

pub trait FilterOpenPGPExt: 'static {
    #[cfg(any(feature = "v3_2", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "v3_2")))]
    #[doc(alias = "g_mime_filter_openpgp_get_begin_offset")]
    fn get_begin_offset(&self) -> i64;

    #[cfg(any(feature = "v3_2", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "v3_2")))]
    #[doc(alias = "g_mime_filter_openpgp_get_data_type")]
    fn get_data_type(&self) -> OpenPGPData;

    #[cfg(any(feature = "v3_2", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "v3_2")))]
    #[doc(alias = "g_mime_filter_openpgp_get_end_offset")]
    fn get_end_offset(&self) -> i64;
}

impl<O: IsA<FilterOpenPGP>> FilterOpenPGPExt for O {
    #[cfg(any(feature = "v3_2", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "v3_2")))]
    fn get_begin_offset(&self) -> i64 {
        unsafe {
            ffi::g_mime_filter_openpgp_get_begin_offset(self.as_ref().to_glib_none().0)
        }
    }

    #[cfg(any(feature = "v3_2", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "v3_2")))]
    fn get_data_type(&self) -> OpenPGPData {
        unsafe {
            from_glib(ffi::g_mime_filter_openpgp_get_data_type(self.as_ref().to_glib_none().0))
        }
    }

    #[cfg(any(feature = "v3_2", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "v3_2")))]
    fn get_end_offset(&self) -> i64 {
        unsafe {
            ffi::g_mime_filter_openpgp_get_end_offset(self.as_ref().to_glib_none().0)
        }
    }
}

impl fmt::Display for FilterOpenPGP {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("FilterOpenPGP")
    }
}
