// This file was generated by gir (https://github.com/gtk-rs/gir @ ad40c01)
// from gir-files (https://github.com/gtk-rs/gir-files @ 5b96546)
// DO NOT EDIT

use glib::object::Cast;
use glib::object::IsA;
use glib::translate::*;
#[cfg(any(feature = "v3_2", feature = "dox"))]
use glib::GString;
use gmime_sys;
use std::fmt;
use Filter;
use FilterGZipMode;

glib_wrapper! {
    pub struct FilterGZip(Object<gmime_sys::GMimeFilterGZip, gmime_sys::GMimeFilterGZipClass, FilterGZipClass>) @extends Filter;

    match fn {
        get_type => || gmime_sys::g_mime_filter_gzip_get_type(),
    }
}

impl FilterGZip {
    pub fn new(mode: FilterGZipMode, level: i32) -> FilterGZip {
        unsafe {
            Filter::from_glib_full(gmime_sys::g_mime_filter_gzip_new(mode.to_glib(), level)).unsafe_cast()
        }
    }
}

pub const NONE_FILTER_GZIP: Option<&FilterGZip> = None;

pub trait FilterGZipExt: 'static {
    #[cfg(any(feature = "v3_2", feature = "dox"))]
    fn get_comment(&self) -> Option<GString>;

    #[cfg(any(feature = "v3_2", feature = "dox"))]
    fn get_filename(&self) -> Option<GString>;

    #[cfg(any(feature = "v3_2", feature = "dox"))]
    fn set_comment(&self, comment: &str);

    #[cfg(any(feature = "v3_2", feature = "dox"))]
    fn set_filename(&self, filename: &str);
}

impl<O: IsA<FilterGZip>> FilterGZipExt for O {
    #[cfg(any(feature = "v3_2", feature = "dox"))]
    fn get_comment(&self) -> Option<GString> {
        unsafe {
            from_glib_none(gmime_sys::g_mime_filter_gzip_get_comment(self.as_ref().to_glib_none().0))
        }
    }

    #[cfg(any(feature = "v3_2", feature = "dox"))]
    fn get_filename(&self) -> Option<GString> {
        unsafe {
            from_glib_none(gmime_sys::g_mime_filter_gzip_get_filename(self.as_ref().to_glib_none().0))
        }
    }

    #[cfg(any(feature = "v3_2", feature = "dox"))]
    fn set_comment(&self, comment: &str) {
        unsafe {
            gmime_sys::g_mime_filter_gzip_set_comment(self.as_ref().to_glib_none().0, comment.to_glib_none().0);
        }
    }

    #[cfg(any(feature = "v3_2", feature = "dox"))]
    fn set_filename(&self, filename: &str) {
        unsafe {
            gmime_sys::g_mime_filter_gzip_set_filename(self.as_ref().to_glib_none().0, filename.to_glib_none().0);
        }
    }
}

impl fmt::Display for FilterGZip {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "FilterGZip")
    }
}
