// This file was generated by gir (https://github.com/gtk-rs/gir @ ad40c01)
// from gir-files (https://github.com/gtk-rs/gir-files @ 5b96546)
// DO NOT EDIT

use glib::object::Cast;
use glib::translate::*;
use gmime_sys;
use std::fmt;
use ContentEncoding;
use Filter;

glib_wrapper! {
    pub struct FilterBasic(Object<gmime_sys::GMimeFilterBasic, gmime_sys::GMimeFilterBasicClass, FilterBasicClass>) @extends Filter;

    match fn {
        get_type => || gmime_sys::g_mime_filter_basic_get_type(),
    }
}

impl FilterBasic {
    pub fn new(encoding: ContentEncoding, encode: bool) -> FilterBasic {
        unsafe {
            Filter::from_glib_full(gmime_sys::g_mime_filter_basic_new(encoding.to_glib(), encode.to_glib())).unsafe_cast()
        }
    }
}

pub const NONE_FILTER_BASIC: Option<&FilterBasic> = None;

impl fmt::Display for FilterBasic {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "FilterBasic")
    }
}
