// This file was generated by gir (https://github.com/gtk-rs/gir @ 00040a2)
// from gir-files (https://github.com/gtk-rs/gir-files @ 5b96546)
// DO NOT EDIT

use crate::Filter;
use glib::object::Cast;
use glib::translate::*;
use std::fmt;

glib::wrapper! {
    pub struct FilterUnix2Dos(Object<ffi::GMimeFilterUnix2Dos, ffi::GMimeFilterUnix2DosClass>) @extends Filter;

    match fn {
        get_type => || ffi::g_mime_filter_unix2dos_get_type(),
    }
}

impl FilterUnix2Dos {
    #[doc(alias = "g_mime_filter_unix2dos_new")]
    pub fn new(ensure_newline: bool) -> FilterUnix2Dos {
        unsafe {
            Filter::from_glib_full(ffi::g_mime_filter_unix2dos_new(ensure_newline.to_glib())).unsafe_cast()
        }
    }
}

pub const NONE_FILTER_UNIX2_DOS: Option<&FilterUnix2Dos> = None;

impl fmt::Display for FilterUnix2Dos {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("FilterUnix2Dos")
    }
}
