// This file was generated by gir (https://github.com/gtk-rs/gir @ 2f0a317)
// from gir-files (https://github.com/gtk-rs/gir-files @ b215ee8)
// DO NOT EDIT

use Filter;
use ffi;
use glib::object::Cast;
use glib::translate::*;
use std::fmt;

glib_wrapper! {
    pub struct FilterDos2Unix(Object<ffi::GMimeFilterDos2Unix, ffi::GMimeFilterDos2UnixClass, FilterDos2UnixClass>) @extends Filter;

    match fn {
        get_type => || ffi::g_mime_filter_dos2unix_get_type(),
    }
}

impl FilterDos2Unix {
    pub fn new(ensure_newline: bool) -> FilterDos2Unix {
        unsafe {
            Filter::from_glib_full(ffi::g_mime_filter_dos2unix_new(ensure_newline.to_glib())).unsafe_cast()
        }
    }
}

pub const NONE_FILTER_DOS2_UNIX: Option<&FilterDos2Unix> = None;

impl fmt::Display for FilterDos2Unix {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "FilterDos2Unix")
    }
}
