// This file was generated by gir (https://github.com/gtk-rs/gir @ 9e3cb65)
// from gir-files (https://github.com/gtk-rs/gir-files @ b215ee8+)
// DO NOT EDIT

use glib::translate::*;
use gmime_sys;

bitflags! {
    pub struct DecryptFlags: u32 {
        const NONE = 0;
        const EXPORT_SESSION_KEY = 1;
    }
}

#[doc(hidden)]
impl ToGlib for DecryptFlags {
    type GlibType = gmime_sys::GMimeDecryptFlags;

    fn to_glib(&self) -> gmime_sys::GMimeDecryptFlags {
        self.bits()
    }
}

#[doc(hidden)]
impl FromGlib<gmime_sys::GMimeDecryptFlags> for DecryptFlags {
    fn from_glib(value: gmime_sys::GMimeDecryptFlags) -> DecryptFlags {
        DecryptFlags::from_bits_truncate(value)
    }
}

bitflags! {
    pub struct FilterBestFlags: u32 {
        const CHARSET = 1;
        const ENCODING = 2;
    }
}

#[doc(hidden)]
impl ToGlib for FilterBestFlags {
    type GlibType = gmime_sys::GMimeFilterBestFlags;

    fn to_glib(&self) -> gmime_sys::GMimeFilterBestFlags {
        self.bits()
    }
}

#[doc(hidden)]
impl FromGlib<gmime_sys::GMimeFilterBestFlags> for FilterBestFlags {
    fn from_glib(value: gmime_sys::GMimeFilterBestFlags) -> FilterBestFlags {
        FilterBestFlags::from_bits_truncate(value)
    }
}

