// This file was generated by gir (https://github.com/gtk-rs/gir @ fe7a6ff+)
// from gir-files (https://github.com/gtk-rs/gir-files @ 33386b3)
// DO NOT EDIT

use Filter;
use NewLineFormat;
use ffi;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::mem;
use std::ptr;

glib_wrapper! {
    pub struct FormatOptions(Boxed<ffi::GMimeFormatOptions>);

    match fn {
        copy => |ptr| gobject_ffi::g_boxed_copy(ffi::g_mime_format_options_get_type(), ptr as *mut _) as *mut ffi::GMimeFormatOptions,
        free => |ptr| gobject_ffi::g_boxed_free(ffi::g_mime_format_options_get_type(), ptr as *mut _),
        get_type => || ffi::g_mime_format_options_get_type(),
    }
}

impl FormatOptions {
    pub fn new() -> FormatOptions {
        unsafe {
            from_glib_full(ffi::g_mime_format_options_new())
        }
    }

    pub fn add_hidden_header(&mut self, header: &str) {
        unsafe {
            ffi::g_mime_format_options_add_hidden_header(self.to_glib_none_mut().0, header.to_glib_none().0);
        }
    }

    pub fn clear_hidden_headers(&mut self) {
        unsafe {
            ffi::g_mime_format_options_clear_hidden_headers(self.to_glib_none_mut().0);
        }
    }

    pub fn clone(&mut self) -> Option<FormatOptions> {
        unsafe {
            from_glib_full(ffi::g_mime_format_options_clone(self.to_glib_none_mut().0))
        }
    }

    pub fn create_newline_filter(&mut self, ensure_newline: bool) -> Option<Filter> {
        unsafe {
            from_glib_full(ffi::g_mime_format_options_create_newline_filter(self.to_glib_none_mut().0, ensure_newline.to_glib()))
        }
    }

    pub fn get_newline(&mut self) -> Option<String> {
        unsafe {
            from_glib_none(ffi::g_mime_format_options_get_newline(self.to_glib_none_mut().0))
        }
    }

    pub fn get_newline_format(&mut self) -> NewLineFormat {
        unsafe {
            from_glib(ffi::g_mime_format_options_get_newline_format(self.to_glib_none_mut().0))
        }
    }

    //pub fn get_param_encoding_method(&mut self) -> /*Ignored*/ParamEncodingMethod {
    //    unsafe { TODO: call ffi::g_mime_format_options_get_param_encoding_method() }
    //}

    pub fn is_hidden_header(&mut self, header: &str) -> bool {
        unsafe {
            from_glib(ffi::g_mime_format_options_is_hidden_header(self.to_glib_none_mut().0, header.to_glib_none().0))
        }
    }

    pub fn remove_hidden_header(&mut self, header: &str) {
        unsafe {
            ffi::g_mime_format_options_remove_hidden_header(self.to_glib_none_mut().0, header.to_glib_none().0);
        }
    }

    pub fn set_newline_format(&mut self, newline: NewLineFormat) {
        unsafe {
            ffi::g_mime_format_options_set_newline_format(self.to_glib_none_mut().0, newline.to_glib());
        }
    }

    //pub fn set_param_encoding_method(&mut self, method: /*Ignored*/ParamEncodingMethod) {
    //    unsafe { TODO: call ffi::g_mime_format_options_set_param_encoding_method() }
    //}

    pub fn get_default() -> Option<FormatOptions> {
        unsafe {
            from_glib_full(ffi::g_mime_format_options_get_default())
        }
    }
}

impl Default for FormatOptions {
    fn default() -> Self {
        Self::new()
    }
}
