// This file was generated by gir (https://github.com/gtk-rs/gir @ 2f0a317)
// from gir-files (https://github.com/gtk-rs/gir-files @ b215ee8)
// DO NOT EDIT

use CryptoContext;
use ffi;
use glib::object::Cast;
use glib::translate::*;
use std::fmt;

glib_wrapper! {
    pub struct GpgContext(Object<ffi::GMimeGpgContext, ffi::GMimeGpgContextClass, GpgContextClass>) @extends CryptoContext;

    match fn {
        get_type => || ffi::g_mime_gpg_context_get_type(),
    }
}

impl GpgContext {
    pub fn new() -> GpgContext {
        unsafe {
            CryptoContext::from_glib_full(ffi::g_mime_gpg_context_new()).unsafe_cast()
        }
    }
}

impl Default for GpgContext {
    fn default() -> Self {
        Self::new()
    }
}

pub const NONE_GPG_CONTEXT: Option<&GpgContext> = None;

impl fmt::Display for GpgContext {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "GpgContext")
    }
}
