// This file was generated by gir (https://github.com/gtk-rs/gir @ 2f0a317)
// from gir-files (https://github.com/gtk-rs/gir-files @ b215ee8)
// DO NOT EDIT

use FormatOptions;
use Stream;
use ffi;
use glib::GString;
use glib::object::IsA;
use glib::translate::*;
use std::fmt;

glib_wrapper! {
    pub struct Header(Object<ffi::GMimeHeader, ffi::GMimeHeaderClass, HeaderClass>);

    match fn {
        get_type => || ffi::g_mime_header_get_type(),
    }
}

pub const NONE_HEADER: Option<&Header> = None;

pub trait HeaderExt: 'static {
    fn format_addrlist<'a, P: Into<Option<&'a FormatOptions>>>(&self, options: P, value: &str, charset: &str) -> Option<GString>;

    fn format_content_disposition<'a, P: Into<Option<&'a FormatOptions>>>(&self, options: P, value: &str, charset: &str) -> Option<GString>;

    fn format_content_type<'a, P: Into<Option<&'a FormatOptions>>>(&self, options: P, value: &str, charset: &str) -> Option<GString>;

    fn format_default<'a, P: Into<Option<&'a FormatOptions>>>(&self, options: P, value: &str, charset: &str) -> Option<GString>;

    fn format_message_id<'a, P: Into<Option<&'a FormatOptions>>>(&self, options: P, value: &str, charset: &str) -> Option<GString>;

    fn format_received<'a, P: Into<Option<&'a FormatOptions>>>(&self, options: P, value: &str, charset: &str) -> Option<GString>;

    fn format_references<'a, P: Into<Option<&'a FormatOptions>>>(&self, options: P, value: &str, charset: &str) -> Option<GString>;

    fn get_name(&self) -> Option<GString>;

    fn get_offset(&self) -> i64;

    fn get_raw_name(&self) -> Option<GString>;

    fn get_raw_value(&self) -> Option<GString>;

    fn get_value(&self) -> Option<GString>;

    fn set_raw_value(&self, raw_value: &str);

    fn set_value<'a, P: Into<Option<&'a FormatOptions>>>(&self, options: P, value: &str, charset: &str);

    fn write_to_stream<'a, P: Into<Option<&'a FormatOptions>>, Q: IsA<Stream>>(&self, options: P, stream: &Q) -> isize;
}

impl<O: IsA<Header>> HeaderExt for O {
    fn format_addrlist<'a, P: Into<Option<&'a FormatOptions>>>(&self, options: P, value: &str, charset: &str) -> Option<GString> {
        let options = options.into();
        unsafe {
            from_glib_full(ffi::g_mime_header_format_addrlist(self.as_ref().to_glib_none().0, mut_override(options.to_glib_none().0), value.to_glib_none().0, charset.to_glib_none().0))
        }
    }

    fn format_content_disposition<'a, P: Into<Option<&'a FormatOptions>>>(&self, options: P, value: &str, charset: &str) -> Option<GString> {
        let options = options.into();
        unsafe {
            from_glib_full(ffi::g_mime_header_format_content_disposition(self.as_ref().to_glib_none().0, mut_override(options.to_glib_none().0), value.to_glib_none().0, charset.to_glib_none().0))
        }
    }

    fn format_content_type<'a, P: Into<Option<&'a FormatOptions>>>(&self, options: P, value: &str, charset: &str) -> Option<GString> {
        let options = options.into();
        unsafe {
            from_glib_full(ffi::g_mime_header_format_content_type(self.as_ref().to_glib_none().0, mut_override(options.to_glib_none().0), value.to_glib_none().0, charset.to_glib_none().0))
        }
    }

    fn format_default<'a, P: Into<Option<&'a FormatOptions>>>(&self, options: P, value: &str, charset: &str) -> Option<GString> {
        let options = options.into();
        unsafe {
            from_glib_full(ffi::g_mime_header_format_default(self.as_ref().to_glib_none().0, mut_override(options.to_glib_none().0), value.to_glib_none().0, charset.to_glib_none().0))
        }
    }

    fn format_message_id<'a, P: Into<Option<&'a FormatOptions>>>(&self, options: P, value: &str, charset: &str) -> Option<GString> {
        let options = options.into();
        unsafe {
            from_glib_full(ffi::g_mime_header_format_message_id(self.as_ref().to_glib_none().0, mut_override(options.to_glib_none().0), value.to_glib_none().0, charset.to_glib_none().0))
        }
    }

    fn format_received<'a, P: Into<Option<&'a FormatOptions>>>(&self, options: P, value: &str, charset: &str) -> Option<GString> {
        let options = options.into();
        unsafe {
            from_glib_full(ffi::g_mime_header_format_received(self.as_ref().to_glib_none().0, mut_override(options.to_glib_none().0), value.to_glib_none().0, charset.to_glib_none().0))
        }
    }

    fn format_references<'a, P: Into<Option<&'a FormatOptions>>>(&self, options: P, value: &str, charset: &str) -> Option<GString> {
        let options = options.into();
        unsafe {
            from_glib_full(ffi::g_mime_header_format_references(self.as_ref().to_glib_none().0, mut_override(options.to_glib_none().0), value.to_glib_none().0, charset.to_glib_none().0))
        }
    }

    fn get_name(&self) -> Option<GString> {
        unsafe {
            from_glib_none(ffi::g_mime_header_get_name(self.as_ref().to_glib_none().0))
        }
    }

    fn get_offset(&self) -> i64 {
        unsafe {
            ffi::g_mime_header_get_offset(self.as_ref().to_glib_none().0)
        }
    }

    fn get_raw_name(&self) -> Option<GString> {
        unsafe {
            from_glib_none(ffi::g_mime_header_get_raw_name(self.as_ref().to_glib_none().0))
        }
    }

    fn get_raw_value(&self) -> Option<GString> {
        unsafe {
            from_glib_none(ffi::g_mime_header_get_raw_value(self.as_ref().to_glib_none().0))
        }
    }

    fn get_value(&self) -> Option<GString> {
        unsafe {
            from_glib_none(ffi::g_mime_header_get_value(self.as_ref().to_glib_none().0))
        }
    }

    fn set_raw_value(&self, raw_value: &str) {
        unsafe {
            ffi::g_mime_header_set_raw_value(self.as_ref().to_glib_none().0, raw_value.to_glib_none().0);
        }
    }

    fn set_value<'a, P: Into<Option<&'a FormatOptions>>>(&self, options: P, value: &str, charset: &str) {
        let options = options.into();
        unsafe {
            ffi::g_mime_header_set_value(self.as_ref().to_glib_none().0, mut_override(options.to_glib_none().0), value.to_glib_none().0, charset.to_glib_none().0);
        }
    }

    fn write_to_stream<'a, P: Into<Option<&'a FormatOptions>>, Q: IsA<Stream>>(&self, options: P, stream: &Q) -> isize {
        let options = options.into();
        unsafe {
            ffi::g_mime_header_write_to_stream(self.as_ref().to_glib_none().0, mut_override(options.to_glib_none().0), stream.as_ref().to_glib_none().0)
        }
    }
}

impl fmt::Display for Header {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "Header")
    }
}
