// This file was generated by gir (https://github.com/gtk-rs/gir @ 00040a2)
// from gir-files (https://github.com/gtk-rs/gir-files @ 5b96546)
// DO NOT EDIT

use crate::InternetAddress;
use glib::object::Cast;
use glib::object::IsA;
use glib::translate::*;
use std::fmt;

glib::wrapper! {
    pub struct InternetAddressMailbox(Object<ffi::InternetAddressMailbox, ffi::InternetAddressMailboxClass>) @extends InternetAddress;

    match fn {
        get_type => || ffi::internet_address_mailbox_get_type(),
    }
}

impl InternetAddressMailbox {
    #[doc(alias = "internet_address_mailbox_new")]
    pub fn new(name: &str, addr: &str) -> InternetAddressMailbox {
        unsafe {
            InternetAddress::from_glib_full(ffi::internet_address_mailbox_new(name.to_glib_none().0, addr.to_glib_none().0)).unsafe_cast()
        }
    }
}

pub const NONE_INTERNET_ADDRESS_MAILBOX: Option<&InternetAddressMailbox> = None;

pub trait InternetAddressMailboxExt: 'static {
    #[doc(alias = "internet_address_mailbox_get_addr")]
    fn get_addr(&self) -> Option<glib::GString>;

    #[doc(alias = "internet_address_mailbox_get_idn_addr")]
    fn get_idn_addr(&self) -> Option<glib::GString>;

    #[doc(alias = "internet_address_mailbox_set_addr")]
    fn set_addr(&self, addr: &str);
}

impl<O: IsA<InternetAddressMailbox>> InternetAddressMailboxExt for O {
    fn get_addr(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::internet_address_mailbox_get_addr(self.as_ref().to_glib_none().0))
        }
    }

    fn get_idn_addr(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::internet_address_mailbox_get_idn_addr(self.as_ref().to_glib_none().0))
        }
    }

    fn set_addr(&self, addr: &str) {
        unsafe {
            ffi::internet_address_mailbox_set_addr(self.as_ref().to_glib_none().0, addr.to_glib_none().0);
        }
    }
}

impl fmt::Display for InternetAddressMailbox {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("InternetAddressMailbox")
    }
}
