// This file was generated by gir (https://github.com/gtk-rs/gir @ 00040a2)
// from gir-files (https://github.com/gtk-rs/gir-files @ 5b96546)
// DO NOT EDIT

use crate::FormatOptions;
use glib::object::IsA;
use glib::translate::*;
use std::fmt;

glib::wrapper! {
    pub struct InternetAddress(Object<ffi::InternetAddress, ffi::InternetAddressClass>);

    match fn {
        get_type => || ffi::internet_address_get_type(),
    }
}

pub const NONE_INTERNET_ADDRESS: Option<&InternetAddress> = None;

pub trait InternetAddressExt: 'static {
    #[doc(alias = "internet_address_get_charset")]
    fn get_charset(&self) -> Option<glib::GString>;

    #[doc(alias = "internet_address_get_name")]
    fn get_name(&self) -> Option<glib::GString>;

    #[doc(alias = "internet_address_set_charset")]
    fn set_charset(&self, charset: Option<&str>);

    #[doc(alias = "internet_address_set_name")]
    fn set_name(&self, name: &str);

    #[doc(alias = "internet_address_to_string")]
    fn to_string(&self, options: Option<&FormatOptions>, encode: bool) -> Option<glib::GString>;
}

impl<O: IsA<InternetAddress>> InternetAddressExt for O {
    fn get_charset(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::internet_address_get_charset(self.as_ref().to_glib_none().0))
        }
    }

    fn get_name(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::internet_address_get_name(self.as_ref().to_glib_none().0))
        }
    }

    fn set_charset(&self, charset: Option<&str>) {
        unsafe {
            ffi::internet_address_set_charset(self.as_ref().to_glib_none().0, charset.to_glib_none().0);
        }
    }

    fn set_name(&self, name: &str) {
        unsafe {
            ffi::internet_address_set_name(self.as_ref().to_glib_none().0, name.to_glib_none().0);
        }
    }

    fn to_string(&self, options: Option<&FormatOptions>, encode: bool) -> Option<glib::GString> {
        unsafe {
            from_glib_full(ffi::internet_address_to_string(self.as_ref().to_glib_none().0, mut_override(options.to_glib_none().0), encode.to_glib()))
        }
    }
}

impl fmt::Display for InternetAddress {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("InternetAddress")
    }
}
