// This file was generated by gir (https://github.com/gtk-rs/gir @ fe7a6ff+)
// from gir-files (https://github.com/gtk-rs/gir-files @ b215ee8)
// DO NOT EDIT

use FormatOptions;
use InternetAddress;
use ParserOptions;
use ffi;
use glib::object::IsA;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::mem;
use std::ptr;

glib_wrapper! {
    pub struct InternetAddressList(Object<ffi::InternetAddressList, ffi::InternetAddressListClass>);

    match fn {
        get_type => || ffi::internet_address_list_get_type(),
    }
}

impl InternetAddressList {
    pub fn new() -> InternetAddressList {
        unsafe {
            from_glib_full(ffi::internet_address_list_new())
        }
    }

    pub fn parse<'a, P: Into<Option<&'a ParserOptions>>>(options: P, str: &str) -> Option<InternetAddressList> {
        let options = options.into();
        unsafe {
            from_glib_full(ffi::internet_address_list_parse(mut_override(options.to_glib_none().0), str.to_glib_none().0))
        }
    }
}

impl Default for InternetAddressList {
    fn default() -> Self {
        Self::new()
    }
}

pub trait InternetAddressListExt {
    fn add<P: IsA<InternetAddress>>(&self, ia: &P) -> i32;

    fn append(&self, append: &InternetAddressList);

    fn clear(&self);

    fn contains<P: IsA<InternetAddress>>(&self, ia: &P) -> bool;

    //fn encode<'a, P: Into<Option<&'a FormatOptions>>>(&self, options: P, str: /*Ignored*/&mut glib::String);

    fn get_address(&self, index: i32) -> Option<InternetAddress>;

    fn index_of<P: IsA<InternetAddress>>(&self, ia: &P) -> i32;

    fn insert<P: IsA<InternetAddress>>(&self, index: i32, ia: &P);

    fn length(&self) -> i32;

    fn prepend(&self, prepend: &InternetAddressList);

    fn remove<P: IsA<InternetAddress>>(&self, ia: &P) -> bool;

    fn remove_at(&self, index: i32) -> bool;

    fn set_address<P: IsA<InternetAddress>>(&self, index: i32, ia: &P);

    fn to_string<'a, P: Into<Option<&'a FormatOptions>>>(&self, options: P, encode: bool) -> String;
}

impl<O: IsA<InternetAddressList>> InternetAddressListExt for O {
    fn add<P: IsA<InternetAddress>>(&self, ia: &P) -> i32 {
        unsafe {
            ffi::internet_address_list_add(self.to_glib_none().0, ia.to_glib_none().0)
        }
    }

    fn append(&self, append: &InternetAddressList) {
        unsafe {
            ffi::internet_address_list_append(self.to_glib_none().0, append.to_glib_none().0);
        }
    }

    fn clear(&self) {
        unsafe {
            ffi::internet_address_list_clear(self.to_glib_none().0);
        }
    }

    fn contains<P: IsA<InternetAddress>>(&self, ia: &P) -> bool {
        unsafe {
            from_glib(ffi::internet_address_list_contains(self.to_glib_none().0, ia.to_glib_none().0))
        }
    }

    //fn encode<'a, P: Into<Option<&'a FormatOptions>>>(&self, options: P, str: /*Ignored*/&mut glib::String) {
    //    unsafe { TODO: call ffi::internet_address_list_encode() }
    //}

    fn get_address(&self, index: i32) -> Option<InternetAddress> {
        unsafe {
            from_glib_none(ffi::internet_address_list_get_address(self.to_glib_none().0, index))
        }
    }

    fn index_of<P: IsA<InternetAddress>>(&self, ia: &P) -> i32 {
        unsafe {
            ffi::internet_address_list_index_of(self.to_glib_none().0, ia.to_glib_none().0)
        }
    }

    fn insert<P: IsA<InternetAddress>>(&self, index: i32, ia: &P) {
        unsafe {
            ffi::internet_address_list_insert(self.to_glib_none().0, index, ia.to_glib_none().0);
        }
    }

    fn length(&self) -> i32 {
        unsafe {
            ffi::internet_address_list_length(self.to_glib_none().0)
        }
    }

    fn prepend(&self, prepend: &InternetAddressList) {
        unsafe {
            ffi::internet_address_list_prepend(self.to_glib_none().0, prepend.to_glib_none().0);
        }
    }

    fn remove<P: IsA<InternetAddress>>(&self, ia: &P) -> bool {
        unsafe {
            from_glib(ffi::internet_address_list_remove(self.to_glib_none().0, ia.to_glib_none().0))
        }
    }

    fn remove_at(&self, index: i32) -> bool {
        unsafe {
            from_glib(ffi::internet_address_list_remove_at(self.to_glib_none().0, index))
        }
    }

    fn set_address<P: IsA<InternetAddress>>(&self, index: i32, ia: &P) {
        unsafe {
            ffi::internet_address_list_set_address(self.to_glib_none().0, index, ia.to_glib_none().0);
        }
    }

    fn to_string<'a, P: Into<Option<&'a FormatOptions>>>(&self, options: P, encode: bool) -> String {
        let options = options.into();
        unsafe {
            from_glib_full(ffi::internet_address_list_to_string(self.to_glib_none().0, mut_override(options.to_glib_none().0), encode.to_glib()))
        }
    }
}
