// This file was generated by gir (https://github.com/gtk-rs/gir @ 00040a2)
// from gir-files (https://github.com/gtk-rs/gir-files @ 5b96546)
// DO NOT EDIT

use crate::Message;
use crate::Object;
use glib::object::IsA;
use glib::translate::*;
use std::fmt;

glib::wrapper! {
    pub struct MessagePart(Object<ffi::GMimeMessagePart, ffi::GMimeMessagePartClass>) @extends Object;

    match fn {
        get_type => || ffi::g_mime_message_part_get_type(),
    }
}

impl MessagePart {
    #[doc(alias = "g_mime_message_part_new")]
    pub fn new(subtype: &str) -> MessagePart {
        unsafe {
            from_glib_full(ffi::g_mime_message_part_new(subtype.to_glib_none().0))
        }
    }

    #[doc(alias = "g_mime_message_part_new_with_message")]
    pub fn with_message<P: IsA<Message>>(subtype: &str, message: &P) -> MessagePart {
        unsafe {
            from_glib_full(ffi::g_mime_message_part_new_with_message(subtype.to_glib_none().0, message.as_ref().to_glib_none().0))
        }
    }
}

pub const NONE_MESSAGE_PART: Option<&MessagePart> = None;

pub trait MessagePartExt: 'static {
    #[doc(alias = "g_mime_message_part_get_message")]
    fn get_message(&self) -> Option<Message>;

    #[doc(alias = "g_mime_message_part_set_message")]
    fn set_message<P: IsA<Message>>(&self, message: &P);
}

impl<O: IsA<MessagePart>> MessagePartExt for O {
    fn get_message(&self) -> Option<Message> {
        unsafe {
            from_glib_none(ffi::g_mime_message_part_get_message(self.as_ref().to_glib_none().0))
        }
    }

    fn set_message<P: IsA<Message>>(&self, message: &P) {
        unsafe {
            ffi::g_mime_message_part_set_message(self.as_ref().to_glib_none().0, message.as_ref().to_glib_none().0);
        }
    }
}

impl fmt::Display for MessagePart {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("MessagePart")
    }
}
