// This file was generated by gir (https://github.com/gtk-rs/gir @ 7f5a2b5)
// from gir-files (https://github.com/gtk-rs/gir-files @ 4740f5e+)
// DO NOT EDIT

mod message;
pub use self::message::Message;
pub use self::message::MessageExt;

#[doc(hidden)]
pub mod traits {
    pub use super::MessageExt;
}
