// This file was generated by gir (https://github.com/gtk-rs/gir @ 00040a2)
// from gir-files (https://github.com/gtk-rs/gir-files @ 5b96546)
// DO NOT EDIT

use crate::CryptoContext;
use glib::object::Cast;
use glib::translate::*;
use std::fmt;

glib::wrapper! {
    pub struct Pkcs7Context(Object<ffi::GMimePkcs7Context, ffi::GMimePkcs7ContextClass>) @extends CryptoContext;

    match fn {
        get_type => || ffi::g_mime_pkcs7_context_get_type(),
    }
}

impl Pkcs7Context {
    #[doc(alias = "g_mime_pkcs7_context_new")]
    pub fn new() -> Pkcs7Context {
        unsafe {
            CryptoContext::from_glib_full(ffi::g_mime_pkcs7_context_new()).unsafe_cast()
        }
    }
}

impl Default for Pkcs7Context {
    fn default() -> Self {
        Self::new()
    }
}

impl fmt::Display for Pkcs7Context {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("Pkcs7Context")
    }
}
