// This file was generated by gir (https://github.com/gtk-rs/gir @ 2f0a317)
// from gir-files (https://github.com/gtk-rs/gir-files @ b215ee8)
// DO NOT EDIT

use Stream;
use ffi;
use gio;
use glib::object::Cast;
use glib::object::IsA;
use glib::translate::*;
use std::fmt;

glib_wrapper! {
    pub struct StreamGIO(Object<ffi::GMimeStreamGIO, ffi::GMimeStreamGIOClass, StreamGIOClass>) @extends Stream;

    match fn {
        get_type => || ffi::g_mime_stream_gio_get_type(),
    }
}

impl StreamGIO {
    pub fn new<P: IsA<gio::File>>(file: &P) -> StreamGIO {
        unsafe {
            Stream::from_glib_full(ffi::g_mime_stream_gio_new(file.as_ref().to_glib_none().0)).unsafe_cast()
        }
    }

    pub fn new_with_bounds<P: IsA<gio::File>>(file: &P, start: i64, end: i64) -> StreamGIO {
        unsafe {
            Stream::from_glib_full(ffi::g_mime_stream_gio_new_with_bounds(file.as_ref().to_glib_none().0, start, end)).unsafe_cast()
        }
    }
}

pub const NONE_STREAM_GIO: Option<&StreamGIO> = None;

pub trait StreamGIOExt: 'static {
    fn get_owner(&self) -> bool;

    fn set_owner(&self, owner: bool);
}

impl<O: IsA<StreamGIO>> StreamGIOExt for O {
    fn get_owner(&self) -> bool {
        unsafe {
            from_glib(ffi::g_mime_stream_gio_get_owner(self.as_ref().to_glib_none().0))
        }
    }

    fn set_owner(&self, owner: bool) {
        unsafe {
            ffi::g_mime_stream_gio_set_owner(self.as_ref().to_glib_none().0, owner.to_glib());
        }
    }
}

impl fmt::Display for StreamGIO {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "StreamGIO")
    }
}
