// This file was generated by gir (https://github.com/gtk-rs/gir @ 7f5a2b5)
// from gir-files (https://github.com/gtk-rs/gir-files @ 4740f5e+)
// DO NOT EDIT

use Stream;
use ffi;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::mem;
use std::ptr;

glib_wrapper! {
    pub struct StreamBuffer(Object<ffi::GMimeStreamBuffer, ffi::GMimeStreamBufferClass>): Stream;

    match fn {
        get_type => || ffi::g_mime_stream_buffer_get_type(),
    }
}

impl StreamBuffer {
    //pub fn new<P: IsA<Stream>>(source: &P, mode: /*Ignored*/StreamBufferMode) -> StreamBuffer {
    //    unsafe { TODO: call ffi::g_mime_stream_buffer_new() }
    //}
}
