// This file was generated by gir (https://github.com/gtk-rs/gir @ fe7a6ff+)
// from gir-files (https://github.com/gtk-rs/gir-files @ 33386b3)
// DO NOT EDIT

use Error;
use Stream;
use ffi;
use glib::object::IsA;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::mem;
use std::ptr;

glib_wrapper! {
    pub struct StreamFile(Object<ffi::GMimeStreamFile, ffi::GMimeStreamFileClass>): Stream;

    match fn {
        get_type => || ffi::g_mime_stream_file_get_type(),
    }
}

impl StreamFile {
    //pub fn new<P: Into<Option</*Unimplemented*/Fundamental: Pointer>>>(fp: P) -> StreamFile {
    //    unsafe { TODO: call ffi::g_mime_stream_file_new() }
    //}

    //pub fn new_with_bounds<P: Into<Option</*Unimplemented*/Fundamental: Pointer>>>(fp: P, start: i64, end: i64) -> StreamFile {
    //    unsafe { TODO: call ffi::g_mime_stream_file_new_with_bounds() }
    //}

    pub fn open(path: &str, mode: &str) -> Result<Stream, Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::g_mime_stream_file_open(path.to_glib_none().0, mode.to_glib_none().0, &mut error);
            if error.is_null() { Ok(from_glib_full(ret)) } else { Err(from_glib_full(error)) }
        }
    }
}

pub trait StreamFileExt {
    fn get_owner(&self) -> bool;

    fn set_owner(&self, owner: bool);
}

impl<O: IsA<StreamFile>> StreamFileExt for O {
    fn get_owner(&self) -> bool {
        unsafe {
            from_glib(ffi::g_mime_stream_file_get_owner(self.to_glib_none().0))
        }
    }

    fn set_owner(&self, owner: bool) {
        unsafe {
            ffi::g_mime_stream_file_set_owner(self.to_glib_none().0, owner.to_glib());
        }
    }
}
