// This file was generated by gir (https://github.com/gtk-rs/gir @ ad40c01)
// from gir-files (https://github.com/gtk-rs/gir-files @ 5b96546)
// DO NOT EDIT

use glib;
use glib::object::Cast;
use glib::object::IsA;
use glib::translate::*;
use gmime_sys;
use std::fmt;
use Stream;

glib_wrapper! {
    pub struct StreamMem(Object<gmime_sys::GMimeStreamMem, gmime_sys::GMimeStreamMemClass, StreamMemClass>) @extends Stream;

    match fn {
        get_type => || gmime_sys::g_mime_stream_mem_get_type(),
    }
}

impl StreamMem {
    pub fn new() -> StreamMem {
        unsafe {
            Stream::from_glib_full(gmime_sys::g_mime_stream_mem_new()).unsafe_cast()
        }
    }

    pub fn with_buffer(buffer: &[u8]) -> StreamMem {
        let len = buffer.len() as usize;
        unsafe {
            Stream::from_glib_full(gmime_sys::g_mime_stream_mem_new_with_buffer(buffer.to_glib_none().0, len)).unsafe_cast()
        }
    }

    pub fn with_byte_array(array: &glib::ByteArray) -> StreamMem {
        unsafe {
            Stream::from_glib_full(gmime_sys::g_mime_stream_mem_new_with_byte_array(array.to_glib_none().0)).unsafe_cast()
        }
    }
}

impl Default for StreamMem {
    fn default() -> Self {
        Self::new()
    }
}

pub const NONE_STREAM_MEM: Option<&StreamMem> = None;

pub trait StreamMemExt: 'static {
    fn get_byte_array(&self) -> Option<glib::ByteArray>;

    fn get_owner(&self) -> bool;

    fn set_byte_array(&self, array: &glib::ByteArray);

    fn set_owner(&self, owner: bool);
}

impl<O: IsA<StreamMem>> StreamMemExt for O {
    fn get_byte_array(&self) -> Option<glib::ByteArray> {
        unsafe {
            from_glib_none(gmime_sys::g_mime_stream_mem_get_byte_array(self.as_ref().to_glib_none().0))
        }
    }

    fn get_owner(&self) -> bool {
        unsafe {
            from_glib(gmime_sys::g_mime_stream_mem_get_owner(self.as_ref().to_glib_none().0))
        }
    }

    fn set_byte_array(&self, array: &glib::ByteArray) {
        unsafe {
            gmime_sys::g_mime_stream_mem_set_byte_array(self.as_ref().to_glib_none().0, array.to_glib_none().0);
        }
    }

    fn set_owner(&self, owner: bool) {
        unsafe {
            gmime_sys::g_mime_stream_mem_set_owner(self.as_ref().to_glib_none().0, owner.to_glib());
        }
    }
}

impl fmt::Display for StreamMem {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "StreamMem")
    }
}
